### ISSUE TITLE
課題4. 本のバーコードをスキャンしてISBN値を元にAmazonの商品ページを表示する

### ISSUE THREAD

**Issue by MinatoIshiwata** [kobayashi-shota/flutter_study#4]
## 条件
- StatefulWidgetの機能を利用すること
- riverpodを利用しないこと
- OSSを利用すること
-  商品ページはWebViewで作成すること
- https://www.amazon.co.jp/dp/${ISBN}を利用すること
## 期限
4日

**Comment by kobayashi-shota** [comment]
メモ
- baseURL: `https://www.amazon.co.jp/dp/`,
- dpParam: スキャンしたバーコード（ean-13）をISBN-10に変換した文字列
  - 変換用のメソッドが必要
